# Generated by Django 5.0.2 on 2024-02-21 05:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('AuthorName', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('RefId', models.CharField(blank=True, max_length=50, null=True)),
                ('CategoryName', models.CharField(blank=True, max_length=300, null=True)),
                ('CategoryIcon', models.FileField(blank=True, null=True, upload_to='category/icon')),
                ('CategoryImage', models.FileField(blank=True, null=True, upload_to='category/image')),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('BookCoverImage', models.FileField(blank=True, null=True, upload_to='book/cover')),
                ('BookCoverImageAlternativeText', models.TextField(blank=True, null=True)),
                ('MinQuantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('UnitPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('DiscountPercent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('OfferPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SubCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('Authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.author')),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('BookRatingId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('User', models.CharField(blank=True, max_length=50, null=True)),
                ('Rating', models.IntegerField(default=0)),
                ('Feedback', models.TextField(blank=True, null=True)),
                ('RatingOn', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('Books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.category'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('BookReviewId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Rating', models.CharField(blank=True, max_length=30, null=True)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('Books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book')),
            ],
        ),
    ]
