# Generated by Django 5.0.2 on 2024-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='AuthorImage',
            field=models.FileField(default=33, upload_to='author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='SEOKeyword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='SEOTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
