# Generated by Django 5.0.2 on 2024-02-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_author_authorimage_book_seokeyword_book_seotitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
