# Generated by Django 5.0.2 on 2024-03-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='MinQuantity',
        ),
        migrations.AddField(
            model_name='book',
            name='Stock',
            field=models.IntegerField(default=33),
            preserve_default=False,
        ),
    ]
