# Generated by Django 5.0.2 on 2024-03-01 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_remove_book_minquantity_book_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('MessageId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('EmailId', models.CharField(blank=True, max_length=150, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Subject', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
